### ISSUE TITLE
Dashboard : Not able to browse and upload image for the user account 

### ISSUE THREAD

**Issue by anvarsha** [bosbangkok/Chillireward_web#32]
PFA

![account holder not able to browse and upload the image](https://cloud.githubusercontent.com/assets/13901526/9603933/96ef31a8-50d1-11e5-9ba5-5c98bcfa06f8.png)

**Comment by yaminiverma88** [comment]
Fixed.
In header, when you refresh the page, updated logo will display.

**Comment by anvarsha** [comment]
This is issue is still there : "Can update the business without uploading business logo which is mandatory"
